name: Build for gh-pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      #- name: Next Build
      #  run: npx next build

      # To fix "_" issues
      - name: Create .nojekyll file
        run: |
          touch build/.nojekyll

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
